// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30rFjtwfIT2x8U1YCXRK8wm06nTrNo-A',
    appId: '1:30884495260:web:d5d50581676776e4261259',
    messagingSenderId: '30884495260',
    projectId: 'taskproof-b2ec8',
    authDomain: 'taskproof-b2ec8.firebaseapp.com',
    storageBucket: 'taskproof-b2ec8.firebasestorage.app',
    measurementId: 'G-25MD3N0MQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDAUBQCDH4jPxcmcTUvo0lv9G9EHd008',
    appId: '1:30884495260:android:9fc4815c17c1ea54261259',
    messagingSenderId: '30884495260',
    projectId: 'taskproof-b2ec8',
    storageBucket: 'taskproof-b2ec8.firebasestorage.app',
  );
}
